### ISSUE TITLE
implement improved auth system

### ISSUE THREAD

**Issue by evillemez** [AmericanCouncils/AyamelResourceApiServer#132]
There needs to be an auth mechanism other than simple API key.  The alternative auth scheme would let client end users communicate directly with the API without having to be forwarded first through the API client server side.  New access tokens would be able to restrict permissions further.

In any case, the most permissive auth token would only allow access to whatever the requesting client has access to.

Here's a general idea of how this could work:

`POST: /api/v1/auth` - in general would receive JSON, but documenting in YAML for nice comments.  This route would require the client's API key and should be made server side.  The resulting auth token could be handed to an end user client (web/mobile).

``` yaml
expires: 1200 #max 3600 seconds or one hour
clientUser:
    id: 1234    #required, if objects are created, the clientUser specified here will be used
    url: 'http://exampleclient.com/users/1234'
resources:
    create:
        allow: true
        filters:
            type: [audio,video]
    delete:
        allow: false
    modify:
        allow: true
        filters:
            clientUser: [] #array of clientUser.ids the user can modify resources for
    view:
        allowed: true
relations:
    create:
        allow: true
        filters:
            type: [transcript_of]
    delete: 
        allow: true
        filters:
            type: [transcript_of]
            clientUser: [1234]
```

The response (201 Created):

``` json
{
    "token": "234tergdfyuigsfdkhj5349e7r43hkfgds923",       #passing this token along in requests 
    "expires": "234565342",                                 #timestamp for when this auth token will expire
    "refresh": "234tergdfyuigsfdkhj5349e7r43hkfgds923"      #refresh token, used to generate new token with the same credentials
}
```

That token can be handed to the end-user client and passed along to the Ayamel API in future requests.  The token could may be be
passed either as a query parameter `?_token=234tergdfyuigsfdkhj5349e7r43hkfgds923` or in a custom header.

"Filters" are arrays of values for resource or relation properties that must match in order for the action to be allowed.  Likely filters would include:
- id
- clientUser
- type
